### ISSUE TITLE
Tags, Theme fields missing from edit-list-page form

### ISSUE THREAD

**Issue by jeffp42ker** [jacobobryant/platypub#69]
In the latest pushes overhauling themes, the `tags` and `theme` fields are missing from the Newsletter edit form.

I'm getting a NPE [here](https://github.com/jacobobryant/platypub/blob/master/src/com/platypub/feat/lists.clj#L35-L38) while creating a new newsletter or editing an existing newsletter due to the `nil` tags value.

PR to add the fields back fixes the issue for me.

**Comment by jacobobryant** [comment]
Oh whoops. I removed them since platypub core doesn't use them anymore (`com.platypub.feat.items/render-email` uses the site's theme for rendering instead of the list's theme, and `com.platypub.util/get-render-opts` uses `:list/sites` to match lists to sites). I made the tags and theme fields optional in the schema but forgot to update `com.platypub.feat.lists/edit-list` so that it doesn't try to set them. Do you have any custom themes that use the tags or theme values? would it be safe to update `edit-list` instead of adding the fields back into the form?

**Comment by jeffp42ker** [comment]
My themes do not depend on those values, it's save to update `edit-list`.

**Comment by jacobobryant** [comment]
Great, I'll push a commit for that and close the PR then. Thanks for noticing this.
